export class LeaveReport {
    APPLICATION_NO
    DATE
    LEAVE_MASTER_ID
    LEAVE_TYPE
    APPLICATION_DATE
    REMARK
    HEAD_STATUS
    HEAD_REMARK
    HEAD_TIME
    HR_STATUS
    HR_REMARK
    HR_TIME
    FINAL_STATUS
    EMPLOYEE_ID
    CLIENT_ID
}
